name: Upload prod Website to S3

on:
  workflow_dispatch:
    inputs:
      invalidate_chache:
        description: 'Invalider le cache'
        required: true
        default: 'false'
        type: boolean
        
  push:
    branches:
    - master
  pull_request:  

jobs:
  check:
    name: Broken Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Broken Link Check
        uses: technote-space/broken-link-checker-action@v2

  deploy:
    name: Déploiement vers S3
    needs: check
    runs-on: ubuntu-latest
    steps:
    - name: Building envirnment
      uses: actions/checkout@master
    - name: Push to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: anjoupleinair.fr
        AWS_ACCESS_KEY_ID: AKIAX3G343OUCKG56Z6K
        AWS_SECRET_ACCESS_KEY: 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
        AWS_REGION: 'eu-west-3'   # optional: defaults to us-east-1
        SOURCE_DIR: 'public'      # optional: defaults to entire repository
        
if: github.event.inputs.invalidate_chache == 'true'
  invalidate-cache:
    name: Invalidation du cache
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@master
    - uses: awact/cloudfront-action@master
      env:
        SOURCE_PATH: './public'
        AWS_REGION: 'us-east-1'
        AWS_ACCESS_KEY_ID: AKIAX3G343OUCKG56Z6K
        AWS_SECRET_ACCESS_KEY: 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
        DISTRIBUTION_ID: E2OMSI4BEAPG05
