name: Deploy PROD website

on:
  workflow_dispatch:
    inputs:
      invalidate_chache:
        description: 'Invalider le cache'
        required: true
        default: 'false'
        type: boolean
        
  push:
    branches:
      - main
    paths:
      - public/**
  #pull_request:  

jobs:
  check:
    name: Broken Link Check
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Broken Link Check
        uses: technote-space/broken-link-checker-action@v2

  deploy:
    name: Déploiement vers AWS
    needs: check
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://anjoupleinair.fr
    steps:
    - name: Building envirnment
      uses: actions/checkout@master
    - name: Push to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: anjoupleinair.fr
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-3'   # optional: defaults to us-east-1
        SOURCE_DIR: 'public'      # optional: defaults to entire repository
        
    - if: github.event.inputs.invalidate_chache == 'true'
      name: Invalidate cache
      uses: awact/cloudfront-action@master
      env:
        SOURCE_PATH: '/'
        AWS_REGION: 'us-east-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
