name: Test AWS OIDC

on:
  workflow_dispatch:
    inputs:
      invalidate_chache:
        description: 'Invalider le cache'
        required: true
        default: 'false'
        type: boolean
        
  #pull_request:  
env:
  AWS_REGION : eu-west-3

jobs:
  aws:
    name: test AWS
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://anjoupleinair.fr
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    steps:
    - name: Building envirnment
      uses: actions/checkout@v2
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
        role-session-name: OIDCSession
        aws-region: 'us-east-1'
